### ISSUE TITLE
Storing the unencrypted key in the config file?!

### ISSUE THREAD

**Issue by Worker3** [ArtisanCode/Log4NetMessageEncryptor#2]
Hi, I am trying to encrypt my config file, or, at least a few critical sections of it
Encryption: 
-> take the section of log4net, encrypt it, store the encrypted text in an appsetting
-> take the section of Log4NetMessageEncryption, encrypt it, store the encrypted text in an appsetting
No issues there.
Decryption:
-> take the crypted text of the appsetting, decrypt it, set up log4net with the xml content (not the app.config)
-> then i want to set the encrytion key, by trying to get the Appender:
`                var rootAppender = ((Hierarchy) LogManager.GetRepository())
                                             .Root.Appenders.OfType<ArtisanCode.Log4NetMessageEncryptor.MessageEncryptingForwardingAppender>()
                                             .FirstOrDefault();

                var x1 = rootAppender.MessageEncryption as RijndaelMessageEncryptor;
                x1.Configuration = new SimpleAesEncryptionConfiguration()
                {
                    EncryptionKey = new EncryptionKeyConfigurationElement(256, "insert key here"),
                };` 
the issue here is: there is no Appender loaded, so i cannot set the key properly

Question: Is there a way to use the encryptor without it ever requiring/writing directly in the App.config?
I am creating Desktopapps and the user easily opens this file and can read the key, and with a little mor effort can decrypt the logs.

**Comment by Tom-Kuhn** [comment]
Hi, 

Thanks for taking the time to try out this library.

When I initially created this library my primary focus was on server side applications which could then use [Aspnet_regiis](http://msdn.microsoft.com/en-US/library/k6h9cz8h(v=vs.100).ASPX ) to safely encrypt the config file.

I hadn't initially considered using this within a desktop application. With the latest version, I don't believe that there is a way of achieving a programmatic solution of setting up the keys.

I will attempt to look into this further and see if there is a solution that will allow you to use this in a desktop environment. 

If this is critical for you, then I always welcome pull requests!

Thanks

Tom Kuhn

**Comment by KeithLJohnson** [comment]
Hi,

My key is encrypted like this...

  <Log4NetMessageEncryption configProtectionProvider="DataProtectionConfigurationProvider">
    <EncryptedData>
      <CipherData>
        <CipherValue>AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAY0Cc+vBd9Eme4B4pQYL1+gQAAAACAAAAAAADZgAAwAAAABAAAABBktlVhpBJbcyL9/L7CJ4cAAAAAASAAACgAAAAEAAAAHW6zOBQHDtB8a/GeE7EVA1oAQAA6EDD6NAIEmgjgV4ARs8lsIWtvrvdmoLkdyIHfxEM7TbZEvu1lz6PpOsakOarPHoWsOb226B/NkrHX5KkS1P6FEDI7YUGS2QJbB4W+xbyLKkHR9FrgD6cMxMwbg5I+KT9NA3UQaDAScz9i4Qg4Aqupo5AW/VnCCGQE6NbjYOyRtLasZTUK+ZARfePSgrwv2crUDz7qAB6BIbFT4Mz7Jk/J+Arayoo50BR8wEu/sXRbqUOjODmMcpwg1NaKEOfTefBvn0bLv5Laljckn7OC3tSovudyXzItJFDC2XDL2d9i9lbVjG1tApkDWseDg76JDjCgURru0JI8PFr1ZcHZf5vn054kMIHQQMHci2x7ENblSSNmn2s0Xs9VbWspGWSzdS0jryfCkPP49viZaHcbhHmByChL2oQTa8tgfd8i1VakQPwqhIFaIIpdh6gU9qkJE65KdyzjBouERQj+1oxB14Rj0qQjI73YEEDFAAAAL7gZVxnzhXK0XIkaZZ7mUWT2Aot</CipherValue>
      </CipherData>
    </EncryptedData>
  </Log4NetMessageEncryption>

Here's how I do it



 private void EncryptLogSettings()
        {
            Configuration config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None);
            ConfigurationSection section = config.GetSection("Log4NetMessageEncryption");
            if (section != null)
            {
                if (!section.SectionInformation.IsProtected)
                {
                    if (!section.ElementInformation.IsLocked)
                    {   // Encrypt the encryption key for logging with machine key and save it to the app config
                        section.SectionInformation.ProtectSection("DataProtectionConfigurationProvider");
                        section.SectionInformation.ForceSave = true;
                        config.Save(ConfigurationSaveMode.Full);
                    }
                }
            }
        }

        private void LoadEncryptedLogSettings()
        {
            Configuration config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None);
            ConfigurationSection section = config.GetSection("Log4NetMessageEncryption");
            if (section != null)
            {
                if (section.SectionInformation.IsProtected)
                {
                    section.SectionInformation.UnprotectSection();
                    // Decrypt to memory and load into log4net encrypting configuration
                    Log4NetMessageEncryptorConfiguration logConfig = (Log4NetMessageEncryptorConfiguration)ConfigurationManager.GetSection("Log4NetMessageEncryption");
                    // Remove unencrypted configuration from memory
                    section = null;
                }
            }
            
        }

Enjoy.

**Comment by Tom-Kuhn** [comment]
Thanks for the update, it's always gratifying seeing others use your library!
